// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt8v2GPZvsD-JwDpx1MX1qO0xLL-gH_yc',
    appId: '1:344892265344:web:1b656a0010dc7159fea765',
    messagingSenderId: '344892265344',
    projectId: 'my-new-flutter-app-12252',
    authDomain: 'my-new-flutter-app-12252.firebaseapp.com',
    storageBucket: 'my-new-flutter-app-12252.firebasestorage.app',
    measurementId: 'G-N4JVYYY658',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdtRPKvAmNCYMqgijmxojIQgtmc-_pork',
    appId: '1:344892265344:android:009fa9dcfe0bb7fefea765',
    messagingSenderId: '344892265344',
    projectId: 'my-new-flutter-app-12252',
    storageBucket: 'my-new-flutter-app-12252.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG7YlVmbew55RAA882fc1kwSCTY7jtr_w',
    appId: '1:344892265344:ios:dbfa63add0683b6cfea765',
    messagingSenderId: '344892265344',
    projectId: 'my-new-flutter-app-12252',
    storageBucket: 'my-new-flutter-app-12252.firebasestorage.app',
    iosBundleId: 'com.example.myNewFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG7YlVmbew55RAA882fc1kwSCTY7jtr_w',
    appId: '1:344892265344:ios:dbfa63add0683b6cfea765',
    messagingSenderId: '344892265344',
    projectId: 'my-new-flutter-app-12252',
    storageBucket: 'my-new-flutter-app-12252.firebasestorage.app',
    iosBundleId: 'com.example.myNewFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt8v2GPZvsD-JwDpx1MX1qO0xLL-gH_yc',
    appId: '1:344892265344:web:940c1bf432889eb8fea765',
    messagingSenderId: '344892265344',
    projectId: 'my-new-flutter-app-12252',
    authDomain: 'my-new-flutter-app-12252.firebaseapp.com',
    storageBucket: 'my-new-flutter-app-12252.firebasestorage.app',
    measurementId: 'G-55B5FCQLS1',
  );
}
